try {
  console.log(i);
}
catch(error) {
  console.log("erreur attrap√©e :", error);
}